### ISSUE TITLE
Undocumented SQL Statement for MySQL, SHOW KEYS

### ISSUE THREAD

**Issue by saklanipankaj** [aprismatic/prismadb#13]
`
 SHOW KEYS FROM t1;`

> +-------+------------+----------+--------------+----------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
> | Table | Non_unique | Key_name | Seq_in_index | Column_name    | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment |
> +-------+------------+----------+--------------+----------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
> | t1    |          0 | PRIMARY  |            1 | prismadb_rowid | A         |          12 |     NULL | NULL   |      | BTREE      |         |               |
> +-------+------------+----------+--------------+----------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
> 1 row in set (0.01 sec)

MySQL Database able to take in this query and pass back an appropriate result, Query undocumented in the WIKI.

**Comment by cheziyi** [comment]
All documented SQL language documented in the wiki are fully supported for use with encrypted databases. Any other queries that are not documented are passed directly to the actual database, which we do not officially support. `SHOW KEYS` is an example of such queries, which we have no guarantee that it will work as expected. That said, supported language syntax is being expanded continuously. This issue is now closed.
